from __future__ import annotations

from .types import TrackPreset, _MASK_PARAMETERS, _csv_p, _json_p, _p

TRACKS: dict[str, TrackPreset] = {
    "mask-refinement": TrackPreset(
        name="mask-refinement",
        description="Sweep silhouette extraction and canonicalization knobs across modes.",
        modes=("profile_loft", "visual_hull_voxel", "ensemble"),
        parameters=_MASK_PARAMETERS,
        default_objective="min_view_iou",
        max_runs_hint=96,
        tags=("mask", "canonicalization"),
    ),
    "profile-loft-refinement": TrackPreset(
        name="profile-loft-refinement",
        description="Tune profile sampling and loft mesh settings for render IoU and editability.",
        modes=("profile_loft",),
        parameters=(
            _p(
                "profile_samples",
                "--profile-samples",
                (80, 120, 160, 240),
                value_type="int",
                group="profile",
            ),
            _p(
                "profile_sample_policy",
                "--profile-sample-policy",
                ("endpoints", "cell_centers"),
                group="profile",
            ),
            _p(
                "profile_fill_strategy",
                "--profile-fill-strategy",
                ("interp_linear", "interp_nearest"),
                group="profile",
            ),
            _p(
                "profile_smoothing_window",
                "--profile-smoothing-window",
                (1, 3, 5, 7),
                value_type="int",
                group="profile",
            ),
            _p(
                "mesh_radial_segments",
                "--mesh-radial-segments",
                (24, 32, 48, 64, 96),
                value_type="int",
                group="mesh",
            ),
            _p(
                "mesh_min_radius",
                "--mesh-min-radius",
                (0.0, 0.0001, 0.001),
                value_type="float",
                group="mesh",
            ),
            _p(
                "mesh_merge_threshold",
                "--mesh-merge-threshold",
                (0.0, 0.0001, 0.001),
                value_type="float",
                group="mesh",
            ),
            _p("mesh_cap_mode", "--mesh-cap-mode", ("fan", "none"), group="mesh"),
            _p(
                "mesh_adaptive_radial_segments",
                "--mesh-adaptive-radial-segments",
                (True, False),
                value_type="bool",
                group="mesh",
            ),
            _p(
                "mesh_shade_smooth",
                "--mesh-shade-smooth",
                (True, False),
                value_type="bool",
                group="mesh",
            ),
        ),
        default_objective="profile_editable",
        max_runs_hint=128,
        tags=("profile", "loft"),
    ),
    "visual-hull-transform": TrackPreset(
        name="visual-hull-transform",
        description="Diagnose visual hull bounds, projection, axis order, scale, and render framing.",
        modes=("visual_hull_voxel",),
        parameters=(
            _p(
                "vh_backend",
                "--vh-backend",
                ("dense", "chunked", "sparse_hash"),
                group="visual_hull",
            ),
            _p(
                "vh_resolution",
                "--vh-resolution",
                (32, 48, 64, 96),
                value_type="int",
                group="visual_hull",
            ),
            _p(
                "vh_chunk_size",
                "--vh-chunk-size",
                (8, 16, 32),
                value_type="int",
                group="visual_hull",
            ),
            _p(
                "vh_mesh_method",
                "--vh-mesh-method",
                ("marching_cubes",),
                group="visual_hull",
            ),
            _p(
                "vh_occupancy_threshold",
                "--vh-occupancy-threshold",
                (0.25, 0.5, 0.75),
                value_type="float",
                group="visual_hull",
            ),
            _p(
                "ref_gray_threshold",
                "--ref-gray-threshold",
                (128,),
                value_type="int",
                group="silhouette",
            ),
            _p(
                "ref_morph_close",
                "--ref-morph-close",
                (5,),
                value_type="int",
                group="silhouette",
            ),
            _p(
                "ref_morph_open",
                "--ref-morph-open",
                (3,),
                value_type="int",
                group="silhouette",
            ),
            _p(
                "ref_fill_holes",
                "--ref-fill-holes",
                (True,),
                value_type="bool",
                group="silhouette",
            ),
            _p(
                "ref_largest_component",
                "--ref-largest-component",
                (True,),
                value_type="bool",
                group="silhouette",
            ),
        ),
        default_search="coordinate",
        default_objective="visual_hull_alignment",
        max_runs_hint=48,
        force_bounds_debug=True,
        tags=("visual-hull", "bounds", "transform"),
    ),
    "visual-hull-quality": TrackPreset(
        name="visual-hull-quality",
        description="Tune visual hull resolution, sparse backend, meshing, postprocess, and uncertainty aggregation.",
        modes=("visual_hull_voxel", "hybrid_loft_hull"),
        parameters=(
            _p(
                "vh_backend",
                "--vh-backend",
                ("chunked", "sparse_hash", "openvdb"),
                group="visual_hull",
            ),
            _p(
                "vh_resolution",
                "--vh-resolution",
                (64, 96, 128, 192),
                value_type="int",
                group="visual_hull",
            ),
            _p(
                "vh_chunk_size",
                "--vh-chunk-size",
                (16, 32),
                value_type="int",
                group="visual_hull",
            ),
            _p(
                "vh_mesh_method",
                "--vh-mesh-method",
                ("marching_cubes", "lewiner"),
                group="visual_hull",
            ),
            _p(
                "vh_postprocess",
                "--vh-postprocess",
                ("none", "poisson", "screened_poisson"),
                group="visual_hull",
            ),
            _p(
                "vh_uncertainty_aggregation",
                "--vh-uncertainty-aggregation",
                ("min", "product", "logit_sum"),
                group="visual_hull",
            ),
        ),
        default_objective="reliability_first",
        max_runs_hint=96,
        force_bounds_debug=True,
        tags=("visual-hull", "quality"),
    ),
    "primitive-fit": TrackPreset(
        name="primitive-fit",
        description="Tune primitive families, target points, primitive counts, and objective weights.",
        modes=("primitive_fit_refine",),
        parameters=(
            _csv_p(
                "primitive_families",
                "--primitive-families",
                (
                    ("superfrustum",),
                    ("ellipsoid",),
                    ("superfrustum", "ellipsoid"),
                    ("superquadric",),
                    ("boxy_superquadric",),
                    ("capsule",),
                    ("superquadric", "superfrustum"),
                    ("boxy_superquadric", "ellipsoid"),
                    ("superfrustum", "superquadric", "ellipsoid"),
                ),
            ),
            _p(
                "primitive_target_points",
                "--primitive-target-points",
                (256, 512, 1024, 2048),
                value_type="int",
            ),
            _p("primitive_min", "--primitive-min", (1, 2, 4), value_type="int"),
            _p("primitive_max", "--primitive-max", (4, 6, 8, 12, 16), value_type="int"),
            _p(
                "primitive_steps",
                "--primitive-steps",
                (0, 5, 10, 25, 50),
                value_type="int",
            ),
            _p(
                "primitive_max_runtime_s",
                "--primitive-max-runtime-s",
                (5.0, 10.0, 20.0),
                value_type="float",
            ),
            _p(
                "primitive_max_objective_evaluations",
                "--primitive-max-objective-evaluations",
                (128, 384, 768, 1536),
                value_type="int",
            ),
            _p(
                "primitive_fail_on_regression",
                "--primitive-fail-on-regression",
                (True, False),
                value_type="bool",
            ),
            _json_p(
                "primitive_loss_weights_json",
                "--primitive-loss-weights-json",
                (
                    {"silhouette": 1.0, "surface": 0.5},
                    {"silhouette": 1.0, "surface": 1.0, "topology": 0.25},
                ),
            ),
        ),
        default_objective="reliability_first",
        max_runs_hint=96,
        tags=("primitive",),
    ),
    "gaussian-proxy": TrackPreset(
        name="gaussian-proxy",
        description="Tune Gaussian/ellipsoid proxy count, initialization, radius, opacity, and mesh export.",
        modes=("gaussian_ellipsoid_proxy",),
        parameters=(
            _p(
                "gaussian_count",
                "--gaussian-count",
                (8, 12, 16, 24, 32, 48),
                value_type="int",
            ),
            _p(
                "gaussian_initialization",
                "--gaussian-initialization",
                ("farthest_point", "kmeans", "grid"),
            ),
            _p(
                "gaussian_min_radius",
                "--gaussian-min-radius",
                (0.0001, 0.001, 0.01),
                value_type="float",
            ),
            _p(
                "gaussian_opacity_min",
                "--gaussian-opacity-min",
                (0.0, 0.1, 0.25),
                value_type="float",
            ),
            _p(
                "gaussian_opacity_max",
                "--gaussian-opacity-max",
                (0.75, 1.0),
                value_type="float",
            ),
            _p(
                "gaussian_export_mesh_proxy",
                "--gaussian-export-mesh-proxy",
                (True,),
                value_type="bool",
            ),
        ),
        default_objective="reliability_first",
        tags=("gaussian", "metric-only-risk"),
    ),
    "differentiable-refine": TrackPreset(
        name="differentiable-refine",
        description="Exercise CPU/GPU differentiable-style refinement and optional dependency policies.",
        modes=("differentiable_refine",),
        parameters=(
            _p(
                "diff_backend",
                "--diff-backend",
                ("cpu_soft_silhouette", "blender_finite_difference", "nvdiffrast"),
            ),
            _p("diff_optional_policy", "--diff-optional-policy", ("skip", "fail")),
            _p(
                "diff_gradient_mode",
                "--diff-gradient-mode",
                ("finite_difference", "backend"),
            ),
            _p(
                "diff_epsilon", "--diff-epsilon", (1e-3, 1e-4, 1e-5), value_type="float"
            ),
            _json_p(
                "diff_loss_weights_json",
                "--diff-loss-weights-json",
                ({"silhouette": 1.0}, {"silhouette": 1.0, "sdf": 0.25}),
            ),
        ),
        default_objective="reliability_first",
        tags=("differentiable", "research"),
    ),
    "ensemble-selection": TrackPreset(
        name="ensemble-selection",
        description="Tune candidate sets and policies so selected ensemble candidates are evidence-backed.",
        modes=("ensemble",),
        parameters=(
            _csv_p(
                "ensemble_candidates",
                "--ensemble-candidates",
                (
                    ("profile_loft", "visual_hull_voxel"),
                    ("profile_loft", "visual_hull_voxel", "gaussian_ellipsoid_proxy"),
                    (
                        "profile_loft",
                        "visual_hull_voxel",
                        "primitive_fit_refine",
                        "gaussian_ellipsoid_proxy",
                        "differentiable_refine",
                    ),
                    ("visual_hull_voxel", "primitive_fit_refine", "shape_program"),
                    (
                        "visual_hull_voxel",
                        "primitive_fit_refine",
                        "gaussian_ellipsoid_proxy",
                        "differentiable_refine",
                        "shape_program",
                    ),
                ),
            ),
            _p(
                "ensemble_policy",
                "--ensemble-policy",
                (
                    "best_score",
                    "balanced",
                    "fidelity",
                    "quality_first",
                    "editable",
                    "editability_first",
                    "printable",
                    "fast_preview",
                    "pareto",
                    "research_fidelity",
                ),
            ),
            _p("primitive_max", "--primitive-max", (6, 12), value_type="int"),
            _p("gaussian_count", "--gaussian-count", (16, 24), value_type="int"),
        ),
        default_objective="reliability_first",
        tags=("ensemble",),
    ),
    "shape-program-editability": TrackPreset(
        name="shape-program-editability",
        description="Emit editable primitive programs and residual patch hints for Blender-first reconstruction.",
        modes=("shape_program", "ensemble"),
        parameters=(
            _p(
                "shape_root_strategy",
                "--shape-root-strategy",
                ("profile_lathe", "bounds_box", "hybrid_profile_bounds"),
                group="shape_program",
            ),
            _p(
                "shape_residual_policy",
                "--shape-residual-policy",
                ("ignore", "report", "suggest_patches"),
                group="shape_program",
            ),
            _p(
                "shape_max_nodes",
                "--shape-max-nodes",
                (24, 48, 64, 96, 128),
                value_type="int",
                group="shape_program",
            ),
            _p(
                "shape_editability_bias",
                "--shape-editability-bias",
                (0.7, 0.85, 1.0),
                value_type="float",
                group="shape_program",
            ),
            _p(
                "shape_compile_blender",
                "--shape-compile-blender",
                (True, False),
                value_type="bool",
                group="shape_program",
            ),
            _p(
                "shape_lathe_segments",
                "--shape-lathe-segments",
                (24, 48, 64, 96),
                value_type="int",
                group="shape_program",
            ),
            _p(
                "shape_bevel_modifier",
                "--shape-bevel-modifier",
                (True, False),
                value_type="bool",
                group="shape_program",
            ),
            _p(
                "shape_weighted_normals",
                "--shape-weighted-normals",
                (True, False),
                value_type="bool",
                group="shape_program",
            ),
            _p(
                "shape_evaluate_texture_materials",
                "--evaluate-texture-materials",
                (True, False),
                value_type="bool",
                group="shape_program",
            ),
            _p(
                "shape_uv_strict",
                "--uv-strict",
                (False, True),
                value_type="bool",
                group="shape_program",
            ),
            _p(
                "shape_material_target",
                "--material-target",
                ("pbr", "simple", "none"),
                group="shape_program",
            ),
            _p(
                "shape_max_texture_memory_mb",
                "--max-texture-memory-mb",
                (32.0, 128.0, 512.0),
                value_type="float",
                group="shape_program",
            ),
            _csv_p(
                "ensemble_candidates",
                "--ensemble-candidates",
                (
                    ("shape_program",),
                    ("visual_hull_voxel", "shape_program"),
                    ("primitive_fit_refine", "shape_program"),
                    ("visual_hull_voxel", "primitive_fit_refine", "shape_program"),
                ),
                group="ensemble",
            ),
            _p(
                "ensemble_policy",
                "--ensemble-policy",
                ("editable", "printable", "research_fidelity"),
                group="ensemble",
            ),
        ),
        default_validation_mode="backend-status",
        default_search="coordinate",
        default_objective="profile_editable",
        max_runs_hint=72,
        force_autopsy=True,
        force_overlays=False,
        tags=("shape-program", "editable", "research"),
    ),
    "content-adaptive-patches": TrackPreset(
        name="content-adaptive-patches",
        description="Drive global-plus-local residual refinement using boundary, SDF, uncertainty, and surface-coverage failures.",
        modes=("ensemble",),
        parameters=(
            _csv_p(
                "ensemble_candidates",
                "--ensemble-candidates",
                (
                    ("visual_hull_voxel", "shape_program"),
                    ("visual_hull_voxel", "primitive_fit_refine", "shape_program"),
                    (
                        "visual_hull_voxel",
                        "primitive_fit_refine",
                        "shape_program",
                        "differentiable_refine",
                    ),
                    (
                        "visual_hull_voxel",
                        "primitive_fit_refine",
                        "gaussian_ellipsoid_proxy",
                        "shape_program",
                        "differentiable_refine",
                    ),
                ),
                group="ensemble",
            ),
            _p(
                "ensemble_policy",
                "--ensemble-policy",
                ("fidelity", "editable", "research_fidelity", "pareto"),
                group="ensemble",
            ),
            _p(
                "shape_residual_policy",
                "--shape-residual-policy",
                ("suggest_patches", "report"),
                group="shape_program",
            ),
            _p(
                "shape_max_nodes",
                "--shape-max-nodes",
                (64, 96, 128),
                value_type="int",
                group="shape_program",
            ),
            _p(
                "shape_editability_bias",
                "--shape-editability-bias",
                (0.85, 1.0),
                value_type="float",
                group="shape_program",
            ),
            _p(
                "shape_evaluate_texture_materials",
                "--evaluate-texture-materials",
                (True,),
                value_type="bool",
                group="shape_program",
            ),
            _p(
                "vh_resolution",
                "--vh-resolution",
                (96, 128, 192),
                value_type="int",
                group="visual_hull",
            ),
            _p(
                "vh_mesh_method",
                "--vh-mesh-method",
                ("lewiner", "marching_cubes"),
                group="visual_hull",
            ),
            _p(
                "vh_uncertainty_aggregation",
                "--vh-uncertainty-aggregation",
                ("product", "logit_sum"),
                group="visual_hull",
            ),
            _p(
                "ref_morph_close",
                "--ref-morph-close",
                (3, 5, 7),
                value_type="int",
                group="silhouette",
            ),
            _p(
                "ref_fill_holes",
                "--ref-fill-holes",
                (True,),
                value_type="bool",
                group="silhouette",
            ),
            _json_p(
                "primitive_loss_weights_json",
                "--primitive-loss-weights-json",
                (
                    {"silhouette": 1.0, "boundary": 0.35, "sdf": 0.25, "surface": 0.5},
                    {
                        "silhouette": 1.0,
                        "boundary": 0.5,
                        "sdf": 0.35,
                        "surface": 0.75,
                        "topology": 0.25,
                    },
                ),
                group="primitive",
            ),
            _json_p(
                "diff_loss_weights_json",
                "--diff-loss-weights-json",
                (
                    {"silhouette": 1.0, "boundary": 0.35, "sdf": 0.35},
                    {"silhouette": 1.0, "boundary": 0.5, "sdf": 0.5},
                ),
                group="differentiable",
            ),
        ),
        default_validation_mode="render-iou",
        default_search="successive_halving",
        default_objective="reliability_first",
        max_runs_hint=160,
        force_bounds_debug=True,
        force_autopsy=True,
        force_overlays=True,
        tags=("content-adaptive-patches", "boundary", "sdf", "detail", "research"),
    ),
    "adversarial-curriculum-hardening": TrackPreset(
        name="adversarial-curriculum-hardening",
        description="Run the progressive synthetic curriculum with strict per-view, topology, editability, uncertainty, and active-view evidence.",
        modes=("ensemble",),
        parameters=(
            _csv_p(
                "ensemble_candidates",
                "--ensemble-candidates",
                (
                    ("profile_loft", "visual_hull_voxel", "shape_program"),
                    ("visual_hull_voxel", "primitive_fit_refine", "shape_program"),
                    (
                        "visual_hull_voxel",
                        "primitive_fit_refine",
                        "gaussian_ellipsoid_proxy",
                        "differentiable_refine",
                        "shape_program",
                    ),
                ),
                group="ensemble",
            ),
            _p(
                "ensemble_policy",
                "--ensemble-policy",
                ("fidelity", "editable", "printable", "research_fidelity", "pareto"),
                group="ensemble",
            ),
            _p(
                "vh_resolution",
                "--vh-resolution",
                (64, 96, 128, 192),
                value_type="int",
                group="visual_hull",
            ),
            _p(
                "vh_postprocess",
                "--vh-postprocess",
                ("none", "smooth_guarded", "topology_repair"),
                group="visual_hull",
            ),
            _p(
                "shape_residual_policy",
                "--shape-residual-policy",
                ("report", "suggest_patches"),
                group="shape_program",
            ),
            _json_p(
                "primitive_loss_weights_json",
                "--primitive-loss-weights-json",
                (
                    {"silhouette": 1.0, "boundary": 0.35, "surface": 0.5},
                    {
                        "silhouette": 1.0,
                        "boundary": 0.5,
                        "sdf": 0.35,
                        "surface": 0.75,
                        "topology": 0.35,
                        "constraint": 0.25,
                    },
                ),
                group="primitive",
            ),
        ),
        default_validation_mode="render-iou",
        default_search="successive_halving",
        default_objective="reliability_first",
        max_runs_hint=216,
        force_bounds_debug=True,
        force_autopsy=True,
        force_overlays=True,
        tags=("adversarial", "curriculum", "active-view", "moonshot"),
    ),
    "sota-metric-bundle": TrackPreset(
        name="sota-metric-bundle",
        description="Exercise full SOTA-style evidence bundles: per-view IoU, boundary IoU, SDF loss, topology, editability, and cost.",
        modes=("ensemble",),
        parameters=(
            _csv_p(
                "ensemble_candidates",
                "--ensemble-candidates",
                (
                    ("visual_hull_voxel", "primitive_fit_refine"),
                    (
                        "visual_hull_voxel",
                        "primitive_fit_refine",
                        "gaussian_ellipsoid_proxy",
                    ),
                    (
                        "visual_hull_voxel",
                        "primitive_fit_refine",
                        "gaussian_ellipsoid_proxy",
                        "differentiable_refine",
                        "shape_program",
                    ),
                ),
                group="ensemble",
            ),
            _p(
                "ensemble_policy",
                "--ensemble-policy",
                ("balanced", "fidelity", "editable", "printable", "research_fidelity"),
                group="ensemble",
            ),
            _p(
                "vh_mesh_method",
                "--vh-mesh-method",
                ("marching_cubes", "lewiner", "dual_contouring"),
                group="visual_hull",
            ),
            _p(
                "vh_uncertainty_aggregation",
                "--vh-uncertainty-aggregation",
                ("min", "product", "logit_sum"),
                group="visual_hull",
            ),
            _json_p(
                "primitive_loss_weights_json",
                "--primitive-loss-weights-json",
                (
                    {"silhouette": 1.0, "boundary": 0.25, "topology": 0.15},
                    {
                        "silhouette": 1.0,
                        "sdf": 0.35,
                        "topology": 0.25,
                        "constraint": 0.2,
                    },
                ),
                group="primitive",
            ),
            _json_p(
                "diff_loss_weights_json",
                "--diff-loss-weights-json",
                (
                    {"silhouette": 1.0, "sdf": 0.25},
                    {"silhouette": 1.0, "boundary": 0.35, "sdf": 0.35},
                ),
                group="differentiable",
            ),
        ),
        default_validation_mode="render-iou",
        default_search="successive_halving",
        default_objective="reliability_first",
        max_runs_hint=144,
        force_bounds_debug=True,
        force_autopsy=True,
        force_overlays=True,
        tags=("sota-metrics", "ensemble", "quality-gate"),
    ),
}
