"""Fresh ownership for one synchronous backend OBJ export, with no reclamation."""
from __future__ import annotations

import json
import os
from pathlib import Path

from utils.artifact_publication import publish_file_no_clobber
from utils.run_ownership import OwnedRun


def _receipt(owner, value):
    payload = (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")
    owner.reserve_bytes(len(payload))
    partial = owner.root / "export-result.json.partial"
    partial.write_bytes(payload)
    os.replace(partial, owner.root / "export-result.json")
    owner.register_file("export-result.json", "diagnostic")


def write_owned_backend_obj(destination, mesh, *, producer, header=(),
                            metadata=None, receipt_artifacts=None) -> Path:
    """Return the actual published path; existing exports remain untouched.

    Only this serialization's fresh stage/receipt are owned. Shared inputs,
    candidate roots, volumes and the backend's other processes are not adopted.
    """
    from .mesh_io import mesh_arrays_from_object, write_obj

    vertices, faces = mesh_arrays_from_object(mesh)
    header = tuple(header)
    metadata = dict(metadata or {})
    header_bytes = sum(len(str(item).encode("utf-8")) + 4 for item in header)
    # Existing OBJ formatting uses three .9g coordinates and decimal indices.
    # Reserve generous space per element, then check actual generated bytes.
    obj_bound = len(vertices) * 96 + sum(len(face) for face in faces) * 32 + header_bytes + 65536
    final = Path(destination)
    final.parent.mkdir(parents=True, exist_ok=True)
    owner = OwnedRun(final.parent.resolve() / ".export-runs", producer=producer,
                     max_generated_bytes=max(16777216, obj_bound + 4194304))
    stage = owner.root / "mesh.obj"
    receipt_path = owner.root / "export-result.json"
    if receipt_artifacts is not None:
        receipt_artifacts["mesh_export_ownership"] = receipt_path
    receipt = {"protocol": "backend-obj-owned-v1", "status": "writing",
               "requested_path": str(final), "stage": stage.name,
               "metadata": metadata, "vertex_count": len(vertices),
               "face_count": len(faces), "subprocesses_started": 0,
               "scope": "one synchronous OBJ export; no backend process-tree ownership",
               "published_path": None}
    error = None
    try:
        _receipt(owner, receipt)
        owner.reserve_bytes(obj_bound)
        write_obj(stage, {"vertices": vertices, "faces": faces}, header=header)
        owner.register_file(stage.name, "final_output")
        destination = final
        for attempt in range(128):
            try:
                publish_file_no_clobber(stage, destination)
                break
            except FileExistsError:
                destination = final.with_name(f"{final.stem}_{attempt + 2}{final.suffix}")
        else:
            raise FileExistsError("backend OBJ publication collision retry bound exceeded")
        # Preserve the final binding even if the separate receipt cannot be
        # written afterward. This metadata owns no external/historical file.
        owner.manifest["published_output"] = {
            "path": str(destination), "bytes": owner.records[stage.name]["bytes"],
            "sha256": owner.records[stage.name]["sha256"], "stage": stage.name,
        }
        receipt.update(status="published", published_path=str(destination),
                       bytes=owner.records[stage.name]["bytes"],
                       sha256=owner.records[stage.name]["sha256"],
                       publication_collisions=attempt)
        return destination
    except BaseException as exc:
        error = exc
        raise
    finally:
        auxiliary = []
        if stage.exists():
            try:
                owner.register_file(stage.name, "final_output" if receipt["published_path"] else "diagnostic")
            except Exception as exc:
                auxiliary.append(exc)
        failure = error or (auxiliary[0] if auxiliary else None)
        receipt.update(status=("cancelled" if isinstance(failure, (KeyboardInterrupt, SystemExit))
                               else "failed" if failure else "succeeded"),
                       error=None if failure is None else repr(failure))
        try:
            _receipt(owner, receipt)
        except Exception as exc:
            auxiliary.append(exc)
            partial = owner.root / "export-result.json.partial"
            if partial.exists():
                try:
                    owner.register_file(partial.name, "diagnostic")
                except Exception as partial_error:
                    auxiliary.append(partial_error)
        owner.auxiliary_errors.extend(repr(exc) for exc in auxiliary)
        try:
            owner.close(error=error or (auxiliary[0] if auxiliary else None))
        except Exception as exc:
            auxiliary.append(exc)
        if error is not None:
            for secondary in auxiliary:
                if hasattr(error, "add_note"):
                    error.add_note("Backend export receipt also failed: " + repr(secondary))
        elif auxiliary:
            raise auxiliary[0]
