"""Isolate extraction, conditioning, optimization and raster conventions.

This reuses one fixed synthetic observation previously generated by the legacy
PIL source projector. It is not held-out reconstruction quality or native input
renderer acceptance. Every metric keeps its identity and original evidence.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys

import numpy as np
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT/'blender_blocking')]
from test_implicit_pipeline import hole_fixture
from reconstruction.implicit.pipeline import prepare_implicit_job, validate_fitted_field, extract_implicit_geometry
from reconstruction.implicit.field_model import NarrowBandField
from reconstruction.implicit.helper import implicit_session, close_implicit_sessions
from reconstruction.projected_metrics import projected_mesh_metrics, projected_mesh_masks
from reconstruction.pixel_projection import canonical_mesh_metrics, canonical_mesh_projections, triangle_pixel_areas, triangle_pixel_centers, LEGACY_METRIC, AREA_METRIC, CENTER_METRIC
from reconstruction.evidence_identity import target_evidence_hash
from reconstruction.pixel_evidence import observed_pixel_evidence
from reconstruction.feature_evidence import known_empty_feature_guard


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--python', required=True)
    parser.add_argument('--output-directory', required=True)
    parser.add_argument('--include-bounded-step-pair', action='store_true')
    args = parser.parse_args()
    root = Path(args.output_directory); root.mkdir(parents=True, exist_ok=True)
    # Save independent analytic counterexamples for a later native renderer
    # check. Pixel coordinates here are integer centers, not cell edges.
    examples = {
        'half_pixel_rectangle': (np.array([[1.5,1.5],[5.5,1.5],[5.5,5.5],[1.5,5.5]]), np.array([[0,1,2],[0,2,3]]), 16.),
        'integer_rectangle': (np.array([[2.,2.],[5.,2.],[5.,5.],[2.,5.]]), np.array([[0,1,2],[0,2,3]]), 9.),
        'half_pixel_triangle': (np.array([[1.5,1.5],[5.5,1.5],[1.5,5.5]]), np.array([[0,1,2]]), 8.),
        'integer_triangle': (np.array([[2.,2.],[5.,2.],[2.,5.]]), np.array([[0,1,2]]), 4.5)}
    analytic_states, analytic_rows = {}, []
    for name, (vertices, faces, expected_area) in examples.items():
        coverage = triangle_pixel_areas(vertices, faces, (8,8))
        centers = triangle_pixel_centers(vertices, faces, (8,8))
        old_canvas = Image.new('1',(8,8));old_draw=ImageDraw.Draw(old_canvas)
        for face in faces:
            old_draw.polygon([tuple(vertices[index]) for index in face],fill=1)
        legacy = np.asarray(old_canvas,bool)
        assert abs(float(coverage.sum())-expected_area) < 1e-12
        alpha = np.uint8(np.rint(coverage*255))
        np.testing.assert_array_equal(alpha>127,coverage>=.5)
        analytic_states.update({name+'_vertices': vertices, name+'_faces': faces,
                               name+'_coverage': coverage, name+'_centers': centers,
                               name+'_legacy': legacy, name+'_alpha_u8': alpha})
        analytic_rows.append({'case': name, 'shape':[8,8], 'expected_geometric_area':expected_area,
                              'actual_area_sum':float(coverage.sum()), 'center_hits':int(centers.sum()),
                              'half_area_hits':int((coverage>=.5).sum()), 'legacy_hits':int(legacy.sum()),
                              'alpha_rounding_threshold_matches_half_area':True})
    np.savez_compressed(root/'analytic-counterexamples.npz',**analytic_states)
    (root/'analytic-counterexamples.json').write_text(json.dumps(analytic_rows,indent=2)+'\n')
    target, seed = hole_fixture()
    reference = target.constraints[0].mask
    evidence = observed_pixel_evidence(target.constraints[0])
    records, pictures = [], []
    def capture(name, geometry, model=None, field=None, fitted=None):
        legacy = projected_mesh_masks(target, geometry.vertices, geometry.faces)['top']
        center = canonical_mesh_projections(target, geometry.vertices, geometry.faces, mode='pixel_centers')['top']
        coverage = canonical_mesh_projections(target, geometry.vertices, geometry.faces)['top']
        masks = [legacy, center >= .5, coverage >= .5]
        for label, mask in zip(('legacy', 'center', 'area-half'), masks):
            Image.fromarray(np.uint8(mask)*255).save(root/(name+'-'+label+'.png'))
        Image.fromarray(np.uint8(np.rint(coverage*255))).save(root/(name+'-continuous-coverage.png'))
        state = {'vertices': geometry.vertices, 'faces': geometry.faces,
                 'reference_hard_mask': reference, 'reference_probability': evidence.foreground,
                 'valid': evidence.valid, 'reliability_weights': evidence.weights,
                 'legacy_mask': legacy, 'center_mask': masks[1], 'area_half_mask': masks[2],
                 'continuous_pixel_coverage': coverage}
        if field is not None:
            state.update(field_zyx=field, seed_field_zyx=model.seed_zyx,
                         origin_xyz=model.origin_xyz, voxel_size_xyz=model.voxel_size_xyz,
                         protected_empty_zyx=model.protected_empty_zyx)
        path = root/(name+'-state.npz'); np.savez_compressed(path, **state)
        record = {'stage': name, 'geometry_hash': geometry.content_hash,
                  'state_sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
                  'known_empty_feature_guard': known_empty_feature_guard(target.constraints[0], masks[2]),
                  'legacy_metrics': projected_mesh_metrics(target, geometry.vertices, geometry.faces)['top'],
                  'center_metrics': canonical_mesh_metrics(target, geometry.vertices, geometry.faces, mode='pixel_centers')['top'],
                  'area_half_and_probability_metrics': canonical_mesh_metrics(target, geometry.vertices, geometry.faces)['top'],
                  'field_constraint': model.report() if model else None,
                  'optimizer': {key: fitted.get(key) for key in ('objective', 'history', 'term_history',
                      'best_evaluation', 'objective_evaluations', 'optimizer_updates', 'stop_reason',
                      'objective_weights', 'known_empty_feature_weight_sum', 'feature_evidence_scope')} if fitted else None}
        records.append(record); pictures.append((name, masks, coverage))
        print('pixel contract stage='+name+' legacy_iou='+str(record['legacy_metrics']['area_iou'])+
              ' area_half_iou='+str(record['area_half_and_probability_metrics']['area_iou']), flush=True)
    try:
        capture('source', seed)
        job, _ = prepare_implicit_job(target, seed, {'execution_approved': True, 'resolution': 32, 'timeout_s': 15.})
        unprotected = NarrowBandField.create(job['seed_field_zyx'], job['voxel_size_xyz'],
            origin_xyz=job['origin_xyz'], band_width=job['band_width'], maximum_displacement=job['maximum_displacement'])
        geometry, _ = extract_implicit_geometry(job['seed_field_zyx'], unprotected)
        capture('unconditioned-extraction', geometry, unprotected, job['seed_field_zyx'])
        owner = implicit_session(args.python)
        stages = [('conditioning-only', 'minimum_distance_rays', 0, {}),
                  ('min-distance-16-updates', 'minimum_distance_rays', 16, {}),
                  ('original-pixel-mesh-16-updates', 'original_pixel_extracted_mesh', 16, {})]
        if args.include_bounded_step_pair:
            stages.extend([('pixel-mesh-step-01', 'original_pixel_extracted_mesh', 16, {'learning_rate': .1}),
                           ('pixel-mesh-step-01-feature', 'original_pixel_extracted_mesh', 16,
                            {'learning_rate': .1, 'known_empty_feature_weight': 1.})])
        for name, objective, steps, options in stages:
            print('pixel contract stage='+name+' preparation', flush=True)
            job, preparation = prepare_implicit_job(target, seed, {'execution_approved': True,
                'resolution': 32, 'objective': objective, 'steps': steps, 'timeout_s': 15., **options})
            fitted = owner.call(job, timeout_s=20.)
            model, field = validate_fitted_field(job, fitted)
            geometry, _ = extract_implicit_geometry(field, model)
            capture(name, geometry, model, field, fitted)
        # All observations are fixed before these experiments. No target is
        # regenerated by a different rasterizer or chosen from an optimizer.
        Image.fromarray(np.uint8(reference)*255).save(root/'fixed-reference.png')
        packet = {'scope': 'one existing bounded synthetic observation; no native renderer/held-out acceptance',
                  'input_origin': 'legacy PIL source projection captured before canonical analysis',
                  'input_evidence_hash': target_evidence_hash(target), 'source_hash': seed.content_hash,
                  'original_camera_specs': {c.view: c.camera.to_dict() for c in target.constraints},
                  'original_target_bounds': target.bounds.to_dict(),
                  'render_contract_sources': ['blender_blocking/integration/blender_ops/render_utils.py',
                                              'blender_blocking/geometry/silhouette_pipeline.py'],
                  'metric_identities': {'legacy': LEGACY_METRIC, 'center': CENTER_METRIC, 'area_half': AREA_METRIC},
                  'continuous_evidence': 'original supplied spatial probabilities and reliability weights retained in every state',
                  'native_renderer_acceptance': 'not_run', 'public_ranking_changed': False,
                  'bounded_step_pair_included': args.include_bounded_step_pair,
                  'quality_and_speed_gains': 'unmeasured outside this diagnostic fixture', 'records': records,
                  'next_native_check': 'render the unchanged source and exact proposals using the existing input camera/alpha/filter settings, preserve raw alpha, and compare original pixel-cell coverage, thresholded alpha and both binary diagnostic tracks'}
        (root/'pixel-contract.json').write_text(json.dumps(packet, indent=2)+'\n')
        tile, row_height = 176, 226
        canvas = Image.new('RGB', (tile*4, row_height*(len(pictures)+1)), '#f4f1e7')
        draw = ImageDraw.Draw(canvas)
        titles = ['legacy endpoint rounding', 'actual pixel centers', 'half cell-area coverage', 'continuous cell coverage']
        for column, title in enumerate(titles):
            draw.text((column*tile+8, 10), title, fill='black')
            ref = Image.fromarray(np.uint8(reference)*255).resize((160, 160), Image.Resampling.NEAREST).convert('RGB')
            canvas.paste(ref, (column*tile+8, 32))
            draw.text((column*tile+8, 198), 'fixed reference', fill='black')
        for index, (name, masks, coverage) in enumerate(pictures, start=1):
            for column, values in enumerate([*masks, coverage]):
                image = Image.fromarray(np.uint8(np.rint(np.asarray(values)*255))).resize((160, 160), Image.Resampling.NEAREST).convert('RGB')
                y = index*row_height
                caption = name.replace('unconditioned-extraction','raw field mesh').replace('conditioning-only','conditioned zero').replace('original-pixel-mesh','pixel mesh').replace('min-distance','min SDF').replace('-16-updates',' 16 updates')
                draw.text((column*tile+8, y+8), caption, fill='black')
                canvas.paste(image, (column*tile+8, y+32))
        canvas.save(root/'source-proposal-pixel-tracks.png')
        print('pixel contract evidence saved', flush=True)
    finally:
        close_implicit_sessions()


if __name__ == '__main__':
    main()
